create table AP_SERVICE_INFO
(
   SERVICE_ID             INTEGER not null auto_increment,
   BUSINESS_NO            VARCHAR(20) not null,
   BUSINESS_TITLE         VARCHAR(100),
   BUSINESS_DEPT_PERSON   VARCHAR(100),
   STATUS                 VARCHAR(10),
   CELLPHONE              VARCHAR(20),
   DEPTCODE               VARCHAR(10),  
   DEPTNAME               VARCHAR(30),
   GUIDECODE			  VARCHAR(10),  
   GUIDENAME			  VARCHAR(50),  
   BUSINESS_TYPE	      VARCHAR(10),
   CREATE_USER_ID         VARCHAR(10),
   CREATE_USER_NAME       VARCHAR(20),
   CREATE_WINDOW_ID       VARCHAR(10),
   CREATE_WINDOW_NAME     VARCHAR(20),
   CREATE_CELLPHONE       VARCHAR(20),
   CREATE_TIME            DATETIME,
   ACCEPT_USER_ID         VARCHAR(10),
   ACCEPT_USER_NAME       VARCHAR(20),
   ACCEPT_WINDOW_ID       VARCHAR(10),
   ACCEPT_WINDOW_NAME     VARCHAR(20),
   ACCEPT_CELLPHONE       VARCHAR(20),
   ACCEPT_TIME            DATETIME,
   REMARK                 VARCHAR(100),
   FILE_ID                VARCHAR(50),
   FILE_NAME              VARCHAR(100),
   primary key (SERVICE_ID)
);
