/* GA_FINANCING_GUIDE */
alter table GA_FINANCING_GUIDE add (
   PUBLISHER            VARCHAR(100),
   PUBLISH_DEPT         VARCHAR(100)
);

/* GA_PARK_QUIT_APPLICATION */
alter table GA_PARK_QUIT_APPLICATION add QUIT_TIME DATETIME; 
alter table GA_PARK_QUIT_APPLICATION add APPROVE_COMMENT VARCHAR(200);

/* GA_PARK_QUIT_GUIDE */
alter table GA_PARK_QUIT_GUIDE add CREATOR_DEPT VARCHAR(100); 
 
/* GA_PM_BILL */
alter table GA_PM_BILL add (
   USAGE_AMOUNT         INTEGER
);

/* GA_REPORT_TEMPLATE */
alter table GA_REPORT_TEMPLATE add (
   PUBLISHER            VARCHAR(100),
   PUBLISH_DEPT_ID      INTEGER,
   PUBLISH_DEPT_NAME    VARCHAR(100)
);
